//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TapPlayer.Maui.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TapPlayer.Maui.Resources.Strings.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About....
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to delete the project &quot;{0}&quot;?.
        /// </summary>
        internal static string AreYouSureYouWantToDeleteTheProject {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteTheProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на background.
        /// </summary>
        internal static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Background playback.
        /// </summary>
        internal static string BackgroundPlayback {
            get {
                return ResourceManager.GetString("BackgroundPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to color for select:.
        /// </summary>
        internal static string ClickToColorForSelect {
            get {
                return ResourceManager.GetString("ClickToColorForSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close the project editor without saving changes..
        /// </summary>
        internal static string CloseProjectEditor {
            get {
                return ResourceManager.GetString("CloseProjectEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close the color selection dialog..
        /// </summary>
        internal static string CloseSelectColor {
            get {
                return ResourceManager.GetString("CloseSelectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close the tile editor without saving changes..
        /// </summary>
        internal static string CloseTileEditor {
            get {
                return ResourceManager.GetString("CloseTileEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Blue.
        /// </summary>
        internal static string ColorBlue {
            get {
                return ResourceManager.GetString("ColorBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark blue.
        /// </summary>
        internal static string ColorBlueDark {
            get {
                return ResourceManager.GetString("ColorBlueDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark blue 25%.
        /// </summary>
        internal static string ColorBlueDark25 {
            get {
                return ResourceManager.GetString("ColorBlueDark25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark blue 50%.
        /// </summary>
        internal static string ColorBlueDark50 {
            get {
                return ResourceManager.GetString("ColorBlueDark50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sea wave.
        /// </summary>
        internal static string ColorBlueGreen {
            get {
                return ResourceManager.GetString("ColorBlueGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark sea wave.
        /// </summary>
        internal static string ColorBlueGreenDark {
            get {
                return ResourceManager.GetString("ColorBlueGreenDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark sea wave 25%.
        /// </summary>
        internal static string ColorBlueGreenDark25 {
            get {
                return ResourceManager.GetString("ColorBlueGreenDark25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark sea wave 50%.
        /// </summary>
        internal static string ColorBlueGreenDark50 {
            get {
                return ResourceManager.GetString("ColorBlueGreenDark50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light sea wave.
        /// </summary>
        internal static string ColorBlueGreenLight {
            get {
                return ResourceManager.GetString("ColorBlueGreenLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light sea wave 50%.
        /// </summary>
        internal static string ColorBlueGreenLight50 {
            get {
                return ResourceManager.GetString("ColorBlueGreenLight50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light blue.
        /// </summary>
        internal static string ColorBlueLight {
            get {
                return ResourceManager.GetString("ColorBlueLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light blue 50%.
        /// </summary>
        internal static string ColorBlueLight50 {
            get {
                return ResourceManager.GetString("ColorBlueLight50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Green.
        /// </summary>
        internal static string ColorGreen {
            get {
                return ResourceManager.GetString("ColorGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark green.
        /// </summary>
        internal static string ColorGreenDark {
            get {
                return ResourceManager.GetString("ColorGreenDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark green 25%.
        /// </summary>
        internal static string ColorGreenDark25 {
            get {
                return ResourceManager.GetString("ColorGreenDark25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark green 50%.
        /// </summary>
        internal static string ColorGreenDark50 {
            get {
                return ResourceManager.GetString("ColorGreenDark50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light green.
        /// </summary>
        internal static string ColorGreenLight {
            get {
                return ResourceManager.GetString("ColorGreenLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light green 50%.
        /// </summary>
        internal static string ColorGreenLight50 {
            get {
                return ResourceManager.GetString("ColorGreenLight50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color palette.
        /// </summary>
        internal static string ColorPalette {
            get {
                return ResourceManager.GetString("ColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Red.
        /// </summary>
        internal static string ColorRed {
            get {
                return ResourceManager.GetString("ColorRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark red.
        /// </summary>
        internal static string ColorRedDark {
            get {
                return ResourceManager.GetString("ColorRedDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark red 25%.
        /// </summary>
        internal static string ColorRedDark25 {
            get {
                return ResourceManager.GetString("ColorRedDark25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark red 50%.
        /// </summary>
        internal static string ColorRedDark50 {
            get {
                return ResourceManager.GetString("ColorRedDark50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light red.
        /// </summary>
        internal static string ColorRedLight {
            get {
                return ResourceManager.GetString("ColorRedLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light red 50%.
        /// </summary>
        internal static string ColorRedLight50 {
            get {
                return ResourceManager.GetString("ColorRedLight50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Violet.
        /// </summary>
        internal static string ColorViolet {
            get {
                return ResourceManager.GetString("ColorViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark violet.
        /// </summary>
        internal static string ColorVioletDark {
            get {
                return ResourceManager.GetString("ColorVioletDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark violet 25%.
        /// </summary>
        internal static string ColorVioletDark25 {
            get {
                return ResourceManager.GetString("ColorVioletDark25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark violet 50%.
        /// </summary>
        internal static string ColorVioletDark50 {
            get {
                return ResourceManager.GetString("ColorVioletDark50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light violet.
        /// </summary>
        internal static string ColorVioletLight {
            get {
                return ResourceManager.GetString("ColorVioletLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light violet 50%.
        /// </summary>
        internal static string ColorVioletLight50 {
            get {
                return ResourceManager.GetString("ColorVioletLight50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sand.
        /// </summary>
        internal static string ColorYellow {
            get {
                return ResourceManager.GetString("ColorYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark sand.
        /// </summary>
        internal static string ColorYellowDark {
            get {
                return ResourceManager.GetString("ColorYellowDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark sand 25%.
        /// </summary>
        internal static string ColorYellowDark25 {
            get {
                return ResourceManager.GetString("ColorYellowDark25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark sand 50%.
        /// </summary>
        internal static string ColorYellowDark50 {
            get {
                return ResourceManager.GetString("ColorYellowDark50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light sand.
        /// </summary>
        internal static string ColorYellowLight {
            get {
                return ResourceManager.GetString("ColorYellowLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light sand 50%.
        /// </summary>
        internal static string ColorYellowLight50 {
            get {
                return ResourceManager.GetString("ColorYellowLight50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create project.
        /// </summary>
        internal static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete project.
        /// </summary>
        internal static string DeleteProject {
            get {
                return ResourceManager.GetString("DeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is playing.
        /// </summary>
        internal static string IsPlaying {
            get {
                return ResourceManager.GetString("IsPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loop.
        /// </summary>
        internal static string Loop {
            get {
                return ResourceManager.GetString("Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Looped playback.
        /// </summary>
        internal static string LoopedPlayback {
            get {
                return ResourceManager.GetString("LoopedPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New project.
        /// </summary>
        internal static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Playback file not selected.
        /// </summary>
        internal static string NoSource {
            get {
                return ResourceManager.GetString("NoSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply changes and close the tile config dialog..
        /// </summary>
        internal static string OkTileEditor {
            get {
                return ResourceManager.GetString("OkTileEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To get started, open a project
        ///or create a new one:.
        /// </summary>
        internal static string OpenOrCreateProjectToStart {
            get {
                return ResourceManager.GetString("OpenOrCreateProjectToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open project.
        /// </summary>
        internal static string OpenProject {
            get {
                return ResourceManager.GetString("OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Play once.
        /// </summary>
        internal static string PlayOnce {
            get {
                return ResourceManager.GetString("PlayOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project name:.
        /// </summary>
        internal static string ProjectNameField {
            get {
                return ResourceManager.GetString("ProjectNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project name is required..
        /// </summary>
        internal static string ProjectNameIsRequired {
            get {
                return ResourceManager.GetString("ProjectNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Projects.
        /// </summary>
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project settings.
        /// </summary>
        internal static string ProjectSettings {
            get {
                return ResourceManager.GetString("ProjectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save changes of project settings..
        /// </summary>
        internal static string SaveProject {
            get {
                return ResourceManager.GetString("SaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select color.
        /// </summary>
        internal static string SelectColor {
            get {
                return ResourceManager.GetString("SelectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected color.
        /// </summary>
        internal static string SelectedColor {
            get {
                return ResourceManager.GetString("SelectedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select file.
        /// </summary>
        internal static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tap on a tile to config:.
        /// </summary>
        internal static string TapToConfig {
            get {
                return ResourceManager.GetString("TapToConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name:.
        /// </summary>
        internal static string TileName {
            get {
                return ResourceManager.GetString("TileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tiles:.
        /// </summary>
        internal static string TilesField {
            get {
                return ResourceManager.GetString("TilesField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tile {0}.
        /// </summary>
        internal static string TileX {
            get {
                return ResourceManager.GetString("TileX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tile settings.
        /// </summary>
        internal static string TitleSettings {
            get {
                return ResourceManager.GetString("TitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to play due to an error.
        /// </summary>
        internal static string UnableToPlay {
            get {
                return ResourceManager.GetString("UnableToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You don&apos;t have any projects yet..
        /// </summary>
        internal static string YouDontHaveAnyProjectsYet {
            get {
                return ResourceManager.GetString("YouDontHaveAnyProjectsYet", resourceCulture);
            }
        }
    }
}
